### ISSUE TITLE
.env - which file?

### ISSUE THREAD

**Issue by Davetbutler** [NillionNetwork/nillion-python-starter#1]
Thank you for reading the docs and suggesting an improvement!

**What section of the docs could be improved? **
I got confused which env file to put my ROOT paths in. What is the difference between `.env` and `.env.sample`

**Comment by oceans404** [comment]
.env is what your computer is reading, and may have sensitive variables you don't want to commit. .env.sample just shows you an example of all the variables that should live in your .env file
