### ISSUE TITLE
[DOCS] - install packages

### ISSUE THREAD

**Issue by Davetbutler** [NillionNetwork/nillion-python-starter#2]
**What section of the docs could be improved? **

I went through the steps in the docs. But it seemed that the py_client was not installed when I ran bootstrap-local-cluster and then the dovtenv was not installed (or requirements.txt was not installed) at any point.

I may have gone through the steps in a wrong order, or made a mistake. But perhaps we can check this when we get a few user testers going through the flow

Is it correct that:
- py_client is installed on bootstrap-local-cluster?
- requirements.txt is installed when I setup virtual env?

**Comment by oceans404** [comment]
Fixed - all dependencies needed are in requirements.txt
