### ISSUE TITLE
[BUG] Millionaire Demo Project error 01_store_secret_party1.py: "storing program: program is not valid: ["io error: "]"

### ISSUE THREAD

**Issue by VladLeustean** [NillionNetwork/nillion-python-starter#28]
**Describe the bug**
When trying to follow the Millionaire demo project on the Nillion.Docs, I came across the error:  "storing program: program is not valid: ["io error: "]" when trying to run the command: python3 01_store_secret_party_1.py

**How to reproduce**
Follow the exact Nillion docs guide:
1. Start the Nillion .venv
2. Run ./bootstrap-local-environment.sh 
3. Run nillion-python-starter/examples_and_tutorials/millionaires_problem_example$ python3 01_store_secret_party1.py 

**Expected behavior**
Expected output is the following:
Storing program in the network: millionaires
[2024-06-11T21:11:30Z ERROR node::managers::compute::handlers::compute] Failed to process message: task StoreProgramCompute<71d3259f-b042-4273-9736-b2ad0cf82161> not found
[2024-06-11T21:11:30Z ERROR node::managers::compute::handlers::compute] Failed to process message: task StoreProgramCompute<71d3259f-b042-4273-9736-b2ad0cf82161> not found
Alice stores millionaires program at program_id: 3PYSzv55jRS4k6nuiF8YgLgruUdgqtobnsnA1oJrTEu21bGdpeBPfGmjw57GRCwXQ5YEbQFaMjS5MjSquF9p7Ynf/millionaires
Alice tells Bob and Charlie her user_id and the millionaires program_id

📋⬇️ Copy and run the following command to store Bob and Charlie's salaries in the network

python3 02_store_secret_party_n.py --user_id_1 3PYSzv55jRS4k6nuiF8YgLgruUdgqtobnsnA1oJrTEu21bGdpeBPfGmjw57GRCwXQ5YEbQFaMjS5MjSquF9p7Ynf --program_id 3PYSzv55jRS4k6nuiF8YgLgruUdgqtobnsnA1oJrTEu21bGdpeBPfGmjw57GRCwXQ5YEbQFaMjS5MjSquF9p7Ynf/millionaires
(.venv) Vladzor-PC:~/nillion-python-starter/examples_and_tutorials/mi

**Screenshots**
https://cdn.discordapp.com/attachments/1204182804817121334/1250185046774775869/image.png?ex=666a050e&is=6668b38e&hm=619b610b20f35cd65e3ab87593f3e932a9de8f8eaa3372cb1758f90f6f74c2e7&)
**Code links**
https://github.com/NillionNetwork/nillion-python-starter/tree/main/examples_and_tutorials/millionaires_problem_example

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS  
 - Browser: Firefox
 - 
**Smartphone (please complete the following information):**

**Additional context**
Managed to fix it by:
1. Opening the 01_store_secret_party1.py file and finding the "program_mir_path = "millionaires.nada.bin"
2. Replacing the variable with the following path: program_mir_path = f"../../programs-compiled/millionaires.nada.bin"

I noticed that this pathing is handled differently in the nillion-python-starter/examples_and_tutorials/core_concept_multi_party_compute
Here, the problem is fixed by adding the nada.bin path to the Config file. I will make a PR with this fix.

**Optional - ETH Address**
Optionally add your ETH Address here.
0x8Ed084fe1502dAF70A1085e1AD6941DbE52D08c8

**Comment by VladLeustean** [comment]
![image](https://github.com/NillionNetwork/nillion-python-starter/assets/27771302/5ad0f440-544d-4b44-99a6-f4276a9c3a8a)

**Comment by oceans404** [comment]
fixed by @VladLeustean
