### ISSUE TITLE
[DOCS] - example programs running not storing program

### ISSUE THREAD

**Issue by Davetbutler** [NillionNetwork/nillion-python-starter#3]
I wonder if in all the files to run programs e.g. `client_single_party_compute/addition_simple.py` we should also add code to upload the program in the file.

Otherwise, users have to store at the cli everytime before they can actually run those files.

The docs walk the user through this step, but it may get annoying for users to always have to store the program from the cli.

However, we should avoid confusion by having the docs tell them to upload from the cli then when they run the python script, it says "storing program". Maybe we have a bit in the python script that checks to see if the program is already stored, and if not, stores it for the user

Just an idea

**Comment by oceans404** [comment]
Done - all examples have store_program in them now
